name: forge
description: A starting point for Dart libraries or applications.
publish_to: none

environment:
  sdk: ^3.9.2

dev_dependencies:
  lints: ^6.0.0

workspace:
  - packages/forge_framework
  - packages/forge_orm
  - packages/forge_orm/example
  - packages/forge_builder
  - packages/forge_flutter
  - packages/forge_flutter/example
  - packages/forge_core
