name: forge_framework
description: Forge Framework is a Dart framework to build server and command line applications faster.
version: 0.1.1
repository: https://github.com/altec-sistemas/forge
resolution: workspace

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  meta: ^1.16.0
  forge_core: any
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  forge_builder: any
  test: ^1.25.8
