name: forge_builder
description: Code generator for Forge framework annotations and dependency injection
version: 1.0.0
resolution: workspace

environment:
  sdk: ^3.9.2

dependencies:
  analyzer: ^8.4.0
  build: ^4.0.2
  build_config: ^1.1.0
  dart_style: ^3.1.2
  forge_core: ^1.0.0
  glob: ^2.1.0
  meta: ^1.16.0
  path: ^1.8.0
  source_gen: ^4.0.2

dev_dependencies:
  build_runner: ^2.4.0
  test: ^1.24.0

# This package is a code generator, so it should be used as a dev_dependency
# in consuming projects:
#
# dev_dependencies:
#   forge_builder: ^1.0.0
#   build_runner: ^2.4.0
