name: forge_builder
description: Code generator for Forge framework annotations and dependency injection
version: 0.1.1
repository: https://github.com/altec-sistemas/forge
resolution: workspace

environment:
  sdk: ^3.9.2

dependencies:
  analyzer: ^7.7.1
  build: ^3.1.0
  build_config: ^1.1.0
  dart_style: ^3.1.1
  forge_core: any
  glob: ^2.1.0
  meta: ^1.16.0
  path: ^1.8.0
  source_gen: ^4.0.0

dev_dependencies:
  build_runner: ^2.4.0
  test: ^1.25.8