name: forge_core
description: Core for forge_framework and forge_flutter packages, including annotations and injector , serialization, validation, etc.
version: 0.1.1
repository: https://github.com/altec-sistemas/forge
resolution: workspace
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  meta: ^1.16.0
  phone_numbers_parser: ^9.0.15
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.8
