name: forge_core
description: A starting point for Dart libraries or applications.
version: 1.0.0
resolution: workspace
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  cpf_cnpj_validator: ^2.0.0
  forge_flutter: any
  logging: ^1.3.0
  meta: ^1.16.0
  phone_numbers_parser: ^9.0.15
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
