name: forge_core
description: Core for forge and forge_flutter packages.
version: 0.1.0
repository: https://github.com/altec-sistemas/forge
resolution: workspace
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  cpf_cnpj_validator: ^2.0.0
  logging: ^1.3.0
  meta: ^1.16.0
  phone_numbers_parser: ^9.0.15
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.8
