name: forge_orm
description: ORM package for forge_framework, including database clients and ORM functionalities.
version: 0.1.0
repository: https://github.com/altec-sistemas/forge
resolution: workspace
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  collection: ^1.19.1
  forge_core: any
  meta: ^1.16.0
  mysql_client_plus: ^0.1.2
  sqlite3: ^2.9.3
  # path: ^1.9.0

dev_dependencies:
  forge_builder: any
  lints: ^6.0.0
  test: ^1.25.6
